version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=HexOceanDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin123#
    ports:
      - "5432:5432"
  web:
    tty: true
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
