# Generated by Django 4.1.7 on 2023-03-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_archive', '0002_alter_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Link_expiration_time',
            new_name='link_expiration_time',
        ),
    ]
